package com.fact.model;

public class AdmMenu {
    private static final long serialVersionUID = 1L;
    public final static String ROLE_PREFIX = "MENU_";

    public final static String MENU_DESIGNING_CI_DATA_MANAGEMENT = "DESIGNING_CI_DATA_MANAGEMENT";
    public final static String MENU_DESIGNING_CI_DATA_ENQUIRY = "DESIGNING_CI_DATA_ENQUIRY";
    public final static String MENU_DESIGNING_CI_INTEGRATED_QUERY_MANAGEMENT = "DESIGNING_CI_INTEGRATED_QUERY_MANAGEMENT";
    public final static String MENU_DESIGNING_CI_INTEGRATED_QUERY_EXECUTION = "DESIGNING_CI_INTEGRATED_QUERY_EXECUTION";

    public final static String MENU_IDC_PLANNING_DESIGN = "IDC_PLANNING_DESIGN";
    public final static String MENU_IDC_RESOURCE_PLANNING = "IDC_RESOURCE_PLANNING";
    public final static String MENU_APPLICATION_ARCHITECTURE_DESIGN = "APPLICATION_ARCHITECTURE_DESIGN";
    public final static String MENU_APPLICATION_ARCHITECTURE_QUERY = "APPLICATION_ARCHITECTURE_QUERY";
    public final static String MENU_APPLICATION_DEPLOYMENT_DESIGN = "APPLICATION_DEPLOYMENT_DESIGN";

    public final static String MENU_CMDB_DESIGNING_ENUM_MANAGEMENT = "CMDB_DESIGNING_ENUM_MANAGEMENT";
    public final static String MENU_CMDB_DESIGNING_ENUM_ENQUIRY = "CMDB_DESIGNING_ENUM_ENQUIRY";

    public final static String MENU_ADMIN_CMDB_MODEL_MANAGEMENT = "ADMIN_CMDB_MODEL_MANAGEMENT";
    public final static String MENU_ADMIN_PERMISSION_MANAGEMENT = "ADMIN_PERMISSION_MANAGEMENT";
    public final static String MENU_ADMIN_USER_PASSWORD_MANAGEMENT = "ADMIN_USER_PASSWORD_MANAGEMENT";
    public final static String MENU_CMDB_ADMIN_BASE_DATA_MANAGEMENT = "CMDB_ADMIN_BASE_DATA_MANAGEMENT";
    public final static String MENU_ADMIN_QUERY_LOG = "ADMIN_QUERY_LOG";
}
